const {uid} = require('uid/secure');

const cmsIdPrefix = 'pc';

export default {
  beforeCreate(event) {
    // Autogenerated data
    event.params.data.cmsId = `${cmsIdPrefix}-${uid(4)}`;

    // Field cleanup
    const {slug, name} = event.params.data;
    event.params.data.name = name.trim();
    event.params.data.slug = slug?.trim() || null;
  },

  async beforeUpdate(event) {
    const {cmsId, slug, name} = event.params.data;

    // Autogenerated data
    if (!cmsId) {
      event.params.data.cmsId = `${cmsIdPrefix}-${uid(4)}`; // Set cmsId
    }

    // Field cleanup
    event.params.data.name = name?.trim() || null;
    event.params.data.slug = slug?.trim() || null;
  },
};
